variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "/certs"
    MYSQL_ROOT_PASSWORD: app
    MYSQL_USER: app
    MYSQL_PASSWORD: app
    MYSQL_DATABASE: shopware
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/
    GIT_STRATEGY: clone
    CHECKOUT_SHOPWARE_BRANCH: "5.6"

stages:
    - Code Style Check
    - Coverage
    - Unit

default:
    image: shopware/5-continuous:7.3
    before_script:
        - zip -rq plugin.zip .
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
        - unzip -q plugin.zip -d shopware/custom/plugins/SwagMigrationConnector
        - cd shopware
        - /entrypoint supervisord &>/dev/null &
        - ./psh.phar init --SW_HOST="localhost"
        - php bin/console sw:plugin:refresh
        - php bin/console sw:plugin:list
        - php bin/console sw:plugin:install --activate SwagMigrationConnector
        - php bin/console sw:cache:clear -e testing

PHP analyze:
    stage: Code Style Check
    before_script: []
    script:
        - zip -rq plugin.zip .
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b ${CHECKOUT_SHOPWARE_BRANCH}
        - unzip -q plugin.zip -d shopware/custom/plugins/SwagMigrationConnector
        - cd shopware
        - /entrypoint supervisord &>/dev/null &
        - cp /usr/local/bin/composer composer.phar
        - php composer.phar install
        - vendor/bin/php-cs-fixer fix --dry-run -v --config=custom/plugins/SwagMigrationConnector/.php_cs.dist --format=junit | tee php-cs-fixer.xml
    artifacts:
        reports:
            junit: shopware/php-cs-fixer.xml

Code Coverage:
    stage: Coverage
    needs: [PHP analyze]
    script:
        - composer require pcov/clobber
        - vendor/bin/pcov clobber
        - cd custom/plugins/SwagMigrationConnector
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-text=build/artifacts/phpunit-coverage-text
        - cat build/artifacts/phpunit-coverage-text | sed -e '/\\Shopware\\.*/d' -e '/\s*Methods:\s*\d*/d'
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    services:
        -   name: mysql:5.7
            alias: mysql
    artifacts:
        paths:
            - shopware/custom/plugins/SwagMigrationConnector/build/artifacts/*
        reports:
            junit: shopware/custom/plugins/SwagMigrationConnector/build/artifacts/phpunit.junit.xml

SW 5.4:
    stage: Unit
    needs: [PHP analyze]
    image: shopware/5-continuous:5.6
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.4"
    script:
        - cd custom/plugins/SwagMigrationConnector
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    services:
        -   name: mysql:5.7
            alias: mysql

SW 5.5:
    stage: Unit
    needs: [PHP analyze]
    image: shopware/5-continuous:5.6
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.5"
    script:
        - cd custom/plugins/SwagMigrationConnector
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    services:
        -   name: mysql:5.7
            alias: mysql

SW 5.6:
    stage: Unit
    needs: [PHP analyze]
    image: shopware/5-continuous:7.2
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.6"
    script:
        - cd custom/plugins/SwagMigrationConnector
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    services:
        -   name: mysql:5.7
            alias: mysql

SW 5.7:
    stage: Unit
    needs: [PHP analyze]
    image: shopware/5-continuous:7.3
    variables:
        CHECKOUT_SHOPWARE_BRANCH: "5.7"
    script:
        - cd custom/plugins/SwagMigrationConnector
        - php ../../../vendor/bin/phpunit
            --configuration phpunit.xml.dist
            --colors=never
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    services:
        -   name: mysql:5.7
            alias: mysql
